Add participant Krishna Singh
jscraftcamp/website pull request #1981
Opened 2024-05-07 17:00 UTC by ultimatekrishna

I would like to register for JS CraftCamp.

- [x] My pull request contains a JSON file `$name_or_nickname.json`
- [x] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
- [x] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [x] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [x] I understand that I might NOT get a T-Shirt, because they might be in production already
- [ ] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/5/views/1)

Are you from a sponsoring company?

- [ ] Yes, I am from company ?????

2024-05-08 10:04 UTC, meldron requested changes
Hi @ultimatekrishna,

looking forward to see you at JSCC. You just have to make some tiny adjustments to your registration json. If you don't have an account or allergy, just leave the string empty, set it to `null` or remove the property.

2024-05-08 10:04 UTC, meldron commented on participants/krishnasingh.json
> +	"allergies": ["-"],
Just leave the array empty

2024-05-08 10:04 UTC, meldron commented on participants/krishnasingh.json
> +	"website": "-"
Leave the string empty or just remove the properties all together.

2024-05-09 00:51 UTC, Narigo commented on participants/krishnasingh.json
> +	"allergies": [""],
Hi @ultimatekrishna , the test was still failing, see https://github.com/jscraftcamp/website/actions/runs/9007558022/job/24756843703

If there are no allergies, please use an empty array or remove the whole field.

```suggestion
	"allergies": [],
```

2024-05-12 10:36 UTC, lowsky approved these changes
Looks good, CU at jscraftcamp

2024-05-12 10:37 UTC, lowsky approved these changes

2024-05-12 10:39 UTC, merged