Create harmeet_singh
jscraftcamp/website pull request #2029
Opened 2024-05-22 19:52 UTC by harmeet24

I would like to register for JS CraftCamp.

- [x] My pull request contains a JSON file `$name_or_nickname.json`
- [x] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
- [x] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a participant.
- [x] I agree that photos and videos might be taken and published (e.g. on social media) during the event.
- [x] I understand that I might NOT get a T-Shirt, because they might be in production already
- [ ] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/7)

Are you from a sponsoring company?

- [ ] Yes, I am from company ?????

2024-05-22 20:24 UTC, meldron requested changes
Hey @harmeet24, please add the json file extension to your newly added file!

2024-05-23 00:13 UTC, Narigo reviewed
Hi @harmeet24 sorry, there is another change to be made. Looks like the `X` value didn't go through - no need for the `@` sign there!

2024-05-23 00:13 UTC, Narigo commented on participants/harmeet_singh.json
> +	"X": "@singh_harmeet13",
I think the `@` sign needs to be removed here

```suggestion
	"X": "singh_harmeet13",
```

2024-05-23 08:53 UTC, harmeet24 commented
> Hi @harmeet24 sorry, there is another change to be made. Looks like the `X` value didn't go through - no need for the `@` sign there!

I fixed the issue, please have a look :)

2024-05-23 09:49 UTC, harmeet24 commented
> Hey @harmeet24, please add the json file extension to your newly added file!

done

2024-05-23 10:25 UTC, meldron approved these changes

2024-05-23 11:10 UTC, merged

2024-05-23 11:10 UTC, meldron commented
Thanks a lot for fixing the PR, welcome to JSCC, see you there!